---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dollqwvj/app
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R .next $DEPLOYPATH/
    - /bin/cp -R public $DEPLOYPATH/
    - /bin/cp -R src $DEPLOYPATH/
    - /bin/cp server.js $DEPLOYPATH/
    - /bin/cp package*.json $DEPLOYPATH/
    - /bin/cp next.config.js $DEPLOYPATH/
    - /bin/cp components.json $DEPLOYPATH/
    - /bin/cp tsconfig.json $DEPLOYPATH/
    - /bin/cp eslint.config.mjs $DEPLOYPATH/
    - /bin/cp postcss.config.mjs $DEPLOYPATH/
