---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dollqwvj/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - source /home/dollqwvj/nodevenv/dollarcv.com/20/bin/activate
    - npm install
    - npm run build