---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dollqwvj/app
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .next $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install --production
